import { Question } from '../../../shared/models/question.model';

export const MOCK_QUESTIONS: Question[] = [
  {
    id: 'question-1',
    type: 'multiple_choice',
    outcomeId: 'outcome-1',
    stem: '15 + 27 işleminin sonucu kaçtır?',
    options: [
      { id: 'opt-1', text: '32', isCorrect: false },
      { id: 'opt-2', text: '42', isCorrect: true },
      { id: 'opt-3', text: '52', isCorrect: false },
      { id: 'opt-4', text: '40', isCorrect: false },
    ],
    solutionExplanation: '15 ile 27 toplanınca 42 elde edilir.',
    difficulty: 'easy',
    tags: ['toplama', 'dört-islem'],
    points: 10,
    publishStatus: 'published',
    currentVersionId: 'qv-1',
    createdAt: '2025-09-03T10:00:00.000Z',
    updatedAt: '2025-09-03T10:00:00.000Z',
    version: 1,
  },
  {
    id: 'question-2',
    type: 'true_false',
    outcomeId: 'outcome-2',
    stem: '-3/4 sayısı sayı doğrusunda 0’ın solunda yer alır.',
    options: [
      { id: 'opt-5', text: 'Doğru', isCorrect: true },
      { id: 'opt-6', text: 'Yanlış', isCorrect: false },
    ],
    solutionExplanation: 'Negatif rasyonel sayılar sıfırın solunda yer alır.',
    difficulty: 'medium',
    tags: ['rasyonel-sayilar'],
    points: 5,
    publishStatus: 'published',
    currentVersionId: 'qv-2',
    createdAt: '2025-09-04T10:00:00.000Z',
    updatedAt: '2025-09-04T10:00:00.000Z',
    version: 1,
  },
  {
    id: 'question-3',
    type: 'essay',
    outcomeId: 'outcome-4',
    stem: 'Bir cismin hızının zamana göre değişimini örnekle açıklayınız.',
    options: [],
    solutionExplanation: 'İvme kavramı, hız-zaman grafiği üzerinden örneklerle anlatılmalıdır.',
    difficulty: 'hard',
    tags: ['hareket', 'kuvvet'],
    points: 20,
    publishStatus: 'draft',
    currentVersionId: 'qv-3',
    createdAt: '2025-09-06T10:00:00.000Z',
    updatedAt: '2025-09-12T10:00:00.000Z',
    version: 2,
  },
];